### ISSUE TITLE
Example of how to run?

### ISSUE THREAD

**Issue by gitonthescene** [ndw/org-to-xml#5]
Hi there,

This sounds interesting to me.  I've been poking around [https://github.com/orgapp/orgajs](orgajs) and was thinking of cross-referencing against what you've done here.  I will have a closer look at the code, but it would be nice if the README.org file gave an example of how to take an org file and generate the XML output.  It would certainly be more inviting for the casual vistor IMHO.

Regards,
-Doug

**Comment by gitonthescene** [comment]
FWIW, it seemed to parse all of the examples from orgajs test cases just fine, though I ran into issues parsing the following if you're curious:

```
% -*- coding: utf-8 -*-
#+LAST_MOBILE_CHANGE: 2020-01-23 15:37:45
#+STARTUP: align fold hidestars oddeven
#+LANGUAGE: en

* Miscellaneous topics
** Time spent
#+BEGIN: clocktable :scope file :maxlevel 3
#+CAPTION: Clock summary at [2020-01-26 Sun 21:06]
| Headline                                      |      Time |       |       |
|-----------------------------------------------+-----------+-------+-------|
| *Total time*                                  | *1d 1:35* |       |       |
|-----------------------------------------------+-----------+-------+-------|
| Miscellaneous topics                          |      5:37 |       |       |
| \_  [[info:eintr][Learn Elisp]]                               |           |  1:07 |       |
| \_  Archive                                   |           |  4:30 |       |
| \_    Make Python script for taking a list... |           |       |  3:08 |
| \_    Download images from...                 |           |       |  0:12 |
| \_    Fix up [[info:screen][screenrc]] to...                   |           |       |  0:43 |
| \_    Figure out what's up with starting a... |           |       |  0:12 |
| \_    Bone up on ssh-keygen                   |           |       |  0:15 |
| Learn Org mode                                |      3:08 |       |       |
| \_  Tasks                                     |           |  1:11 |       |
| \_    Archive                                 |           |       |  1:11 |
| Git hook manager                              |      2:04 |       |       |
| \_  Archive                                   |           |  1:38 |       |
| \_    Learn about...                          |           |       |  1:38 |
| Finances                                      |      0:39 |       |       |
| \_  File FBAR                                 |           |  0:39 |       |
| Proposed project?                             |     14:07 |       |       |
| \_  Review Tokyo Gaijins site                 |           | 14:07 |       |
| \_    Mock up reservation page in React       |           |       | 10:05 |
#+END:

```

**Comment by ndw** [comment]
I'll update the README with explicit usage instructions and take a look at this issue asap.

**Comment by ndw** [comment]
What's curious is, I tried the test case and got an error. I started poking around to more precisely identify the problem. And the problem went away. I can't even reproduce it on a clean start of emacs. Very puzzling. Will continue to search.

**Comment by gitonthescene** [comment]
Oh!  I actually just realized I was using org-to-xml and not om-to-xml.  The latter seems to work, but I'm getting errors from the former.  By way of excuse, I had no instructions to follow so I just used what seemed natural.  In the spirit of community, it might be nice to have a link to [the om project](https://github.com/ndwarshuis/om.el) from your README.org.

In any event, thanks for getting back to me.

**Comment by ndw** [comment]
I believe there's already a link to the OM project in the README. I've updated the README a little bit and removed org-to-xml.el from the repository. Thanks for your feedback.

**Comment by gitonthescene** [comment]
No worries.  Thanks for your attention.

**Comment by gitonthescene** [comment]
Incidentally, I don't know where your interests lie, but I have a feeling you might find [the unified](https://github.com/unifiedjs/unified) project interesting.  It's javascript based, but there are lots of tools around syntax parsing.  The xast suite can convert from XML to the json trees they use there.
